language: python
fast_finish: true

python:
  - 3.6

os:
  - linux
  
notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - gcc

before_install:
  - pip -q install coveralls

install: python setup.py develop

script: coverage run tests/test.py -v

after_success: coveralls

