language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - gcc

install: pip -q install -e .[tests]

script: 
  - pytest
  - coverage run tests/test_all.py -v

after_success: coveralls
